# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0fbe7bedd0ac0f2a7d2e9477cd46ae4c"
name = "walmart-mcs-marketplace"
application_url = "https://walmart-mcs-marketplace.vercel.app/"
embedded = true
handle = "walmart-mcs-marketplace"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "returns/request" ]
  uri = "/webhooks/returns/request"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_fulfillments,read_orders,read_inventory,write_inventory,read_returns,write_returns,write_assigned_fulfillment_orders,read_locations,write_files,read_files,read_customers,write_orders,read_fulfillment_orders"

[auth]
redirect_urls = [ 
  "https://walmart-mcs-marketplace.vercel.app/auth/callback",
  "https://walmart-mcs-marketplace.vercel.app/auth/shopify/callback", 
  "https://walmart-mcs-marketplace.vercel.app/api/auth/callback",
  "https://walmart-mcs-marketplace.vercel.app/api/auth"
]
